version: 2
project_name: shoes-vz

before:
  hooks:
    - go mod tidy
    - buf generate

builds:
  - id: shoes-vz-agent
    main: ./cmd/shoes-vz-agent
    binary: shoes-vz-agent
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w

  - id: shoes-vz-runner-agent
    main: ./cmd/shoes-vz-runner-agent
    binary: shoes-vz-runner-agent
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w

dockers:
  - image_templates:
      - "ghcr.io/whywaita/shoes-vz-server:{{ .Tag }}"
      - "ghcr.io/whywaita/shoes-vz-server:v{{ .Major }}"
      - "ghcr.io/whywaita/shoes-vz-server:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/whywaita/shoes-vz-server:latest"
    dockerfile: Dockerfile.server
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description=shoes-vz-server"
      - "--label=org.opencontainers.image.url=https://github.com/whywaita/shoes-vz"
      - "--label=org.opencontainers.image.source=https://github.com/whywaita/shoes-vz"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.licenses=MIT"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  prerelease: auto
