version: 2
project_name: shoes-vz

before:
  hooks:
    - go mod tidy
    - make deps
    - make generate

builds:
  - id: shoes-vz-agent
    main: ./cmd/shoes-vz-agent
    binary: shoes-vz-agent
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w

  - id: shoes-vz-runner-agent
    main: ./cmd/shoes-vz-runner-agent
    binary: shoes-vz-runner-agent
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w

  - id: shoes-vz-client
    main: ./cmd/shoes-vz-client
    binary: shoes-vz-client
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w

archives:
  - format: binary
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  prerelease: auto
